treesitter = {
		TSComment            = { fg = c.c0, },
		TSAnnotation         = { fg = c.bg5, },
		TSAttribute          = { fg = c.fg2, },
		TSConstructor        = { fg = c.g2, },
		TSType               = { fg = c.g1, },
		TSTypeBuiltin        = { fg = c.g1, },
		TSConditional        = { fg = c.y1, },
		TSException          = { fg = c.r2, },
		TSInclude            = { fg = c.m0, },
		TSKeywordReturn      = { fg = c.y2, },
		TSKeyword            = { fg = c.y1, },
		TSKeywordFunction    = { fg = c.y1, },
		TSLabel              = { fg = c.m1, },
		TSNamespace          = { fg = c.m1, },
		TSRepeat             = { fg = c.y1, },
		TSConstant           = { fg = c.b1, },
		TSConstBuiltin       = { fg = c.b1, },
		TSFloat              = { fg = c.m3, },
		TSNumber             = { fg = c.m3, },
		TSBoolean            = { fg = c.m3, },
		TSCharacter          = { fg = c.m3, },
		TSError              = { fg = c.r1, },
		TSFunction           = { fg = c.g1, },
		TSFuncBuiltin        = { fg = c.g1, },
		TSMethod             = { fg = c.g1, },
		TSConstMacro         = { fg = c.c2, },
		TSFuncMacro          = { fg = c.c2, },
		TSVariable           = { fg = c.fg1, },
		TSVariableBuiltin    = { fg = c.fg1, },
		TSProperty           = { fg = c.m1, },
		TSOperator           = { fg = c.bg5, },
		TSField              = { fg = c.fg1, },
		TSParameter          = { fg = c.fg1, },
		TSParameterReference = { fg = c.fg1, },
		TSSymbol             = { fg = c.fg1, },
		TSText               = { fg = c.fg1, },
		TSPunctDelimiter     = { fg = c.fg1, },
		TSTagDelimiter       = { fg = c.bg5, },
		TSTagAttribute       = { fg = c.bg5, },
		TSPunctBracket       = { fg = c.bg5, },
		TSPunctSpecial       = { fg = c.bg5, },
		TSString             = { fg = c.b3, },
		TSStringRegex        = { fg = c.b3, },
		TSStringEscape       = { fg = c.b3, },
		TSTag                = { fg = c.m1, },
		TSEmphasis           = { style = "italic", },
		TSUnderline          = { style = "underline", },
		TSTitle              = { fg = c.fg1, },
		TSLiteral            = { fg = c.y1, },
		TSURI                = { fg = c.b1, style = "underline", },
		TSKeywordOperator    = { fg = c.b1, },
		TSStructure          = { fg = c.b1, },
		TSStrong             = { fg = c.b1, style = "bold", },
		TSQueryLinterError   = { fg = c.r1, },
		TreesitterContext    = { bg = c.bg5, },
}

return treesitter
